### ISSUE TITLE
1.0.1.Release setup issue

### ISSUE THREAD

**Issue by pkonka** [DICE-UNC/irods-cloud-browser#170] opened 2016-07-07 17:18 UTC
I am trying to setup 1.0.1.Release. Followed instructions to setup Tomcat7 and Apache2. I am getting blank screen when I tried to browse the application. I don't see any issues in apache2 or tomcat7 logs.

![cloud-browser](https://cloud.githubusercontent.com/assets/3237035/16662335/1a46cc02-4445-11e6-8187-0a6d15f1f5c4.png)

**Comment by rwmoore** [comment] 2016-07-07 17:23
I had a similar problem, solved by clearing the browser cache.

Reagan Moore

**Comment by michael-conway** [comment] 2016-07-07 17:23
This is highly likely caused by the front end (the javascript) not being
able to find the back end.

go into the front-end code (the stuff on apache web server) into
irods-cloud-frontend/app/components/globals.js

var HOST = "http://"+location.hostname+":8080/irods-cloud-backend/";


Should be updated to the host/port where your back end exists. I think
that's your issue.

Sorry to the world that the installs are overly convoluted, this is
specifically being addressed in this next milestone.

**Comment by pkonka** [comment] 2016-07-07 17:31
I have it set as follows.  
var HOST = "http://localhost:8080/irods-cloud-backend/";

![image](https://cloud.githubusercontent.com/assets/3237035/16662739/df49875a-4446-11e6-97ae-51a804f34d40.png)

**Comment by michael-conway** [comment] 2016-07-07 17:34
Are you just testing locally? That is, is the irods-cloud-backend app
running on the same box?

**Comment by pkonka** [comment] 2016-07-07 17:35
Yes. Both frontend and backend are running on the same box.

**Comment by michael-conway** [comment] 2016-07-07 17:43
A colleague notes that you have the tomcat url as httpS:  is that the issue?

I'm on Linux, which, alas, doesn't like WebEx.

MC

**Comment by pkonka** [comment] 2016-07-07 17:46
I tried both http and https. Same issue.

**Comment by chexare** [comment] 2016-07-07 17:59
Hello pkonka,

To get a better sense of where this error is coming from, can you go to the
page that shows you the error message again and with the web tools of your
browser, bring up the console of the browser and get a screenshot of that
please.

CG

**Comment by JustinKyleJames** [comment] 2016-07-07 18:08
You could also try going directly to the backend with something like the following:

https://ec2-96-127-51-47.us-gov-west-1.compute.amazonaws.com/irods-cloud-backend/initialConf

**Comment by JustinKyleJames** [comment] 2016-07-07 18:13
Accidentally closed this.  Reopening.

**Comment by michael-conway** [comment] 2016-07-07 18:19
The issue here is that the front end cannot contact the back end

1) an issue with the aforementioned globals.js.
2) an issue with the cloud backend being unresponsive (did it successfully
deploy?  Did tomcat run?  Is tomcat set to listen to 8080 versus , say ajp?
3) a browser cache issue of old javascripts.

That seems to be the universe of possibilities we can sift through!

On firefox or chrome, I would recommend using the developer tools/console
to check to see what network calls are being made from the browser to the
backend, and what errors or issues have arisen from those calls failing.  I
think it's just that the front end is not talking to the back end.

**Comment by pkonka** [comment] 2016-07-07 18:50
Yes. The issue seems to be frontend failing to connect to the backend. Here is the screenshot of the browser console. 

![image](https://cloud.githubusercontent.com/assets/3237035/16665436/a48d389a-4451-11e6-8e59-4ed738f0d7ce.png)

**Comment by michael-conway** [comment] 2016-07-07 18:53
ahh!

Are you downloading this content ( the front end) from an external https
server and then having it go to your local tomcat?  Thanks for that info,
yes, it's usually just browsers unhappy about http protocols or settings...

**Comment by chexare** [comment] 2016-07-07 19:00
Ok so, first it seem like your globals.js keeps trying to call for a "HTTP" url rather than "HTTPS" check on that again, and it also seems like you are not running the latest version of the cloud browser, the new release has the version on top of the irods footer tag as you can see in the image below, make sure to download the 1.0.1-RELEASE packages from:
https://github.com/DICE-UNC/irods-cloud-browser/releases
<img width="277" alt="screen shot 2016-07-07 at 2 52 11 pm" src="https://cloud.githubusercontent.com/assets/3952504/16665852/17937e5c-4453-11e6-92e4-549a1a93ddca.png">

**Comment by michael-conway** [comment] 2016-07-07 19:23
Today is bad, but I'd be happy tomorow to do a google chat and screen
share.  As I said, webex doesn't really work from linux desktops

**Comment by chexare** [comment] 2016-08-19 18:18
Closing as a config issue, if your issue still persist, please reopen this ticket.

**Closed by chexare** 2016-08-19 18:18 UTC
